---
#
# Update packages
###############################################################################
- name: Updating all the packages for Ubuntu/Debian System
  apt:
    upgrade: full
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install the default packages for CentOS/RedHat System
  yum:
    name: "{{ centos }}"
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Install the default packages for Debian/Ubuntu System
  apt:
    name: "{{ debian }}"
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Updating all the packages for CentOS/RedHat System
  yum:
    name: "*"
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Install EPEL release for RedHat System
  ansible.builtin.yum:
    name: epel-release
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Install the default packages for the playbook
  package:
    name: "{{ multidist }}"
    state: latest

#
# Timezone and Clock
################################################################################
- name: Install NTP package for Debian/Ubuntu
  ansible.builtin.apt:
    name: ntp
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Chrony package for CentOS/RedHat
  ansible.builtin.yum:
    name: chrony
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Changing the timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Configuring NTP Client
  copy:
    src: ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0640
  when: ansible_os_family == "RedHat"

- name: Creating the drift file for the NTP service
  file:
    path: /etc/drift
    state: touch
    owner: root
    group: root
    mode: 0640
  when: ansible_os_family == "RedHat"

#
# Hostname and Network
################################################################################
- name: Changing the hostname
  hostname:
    name: '{{ hostname }}.{{ domain }}'

- name: Including the hostname in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1 {{ hostname }}.{{ domain }} {{ hostname }}'
    state: present
  when: ansible_virtualization_type != "docker"

#
# Enable services
################################################################################
- name: Enabling all services - Systemd way
  systemd:
    daemon_reload: yes
    state: started
    enabled: yes
    name: "{{ 'ntp' if ansible_os_family == 'Debian' else 'chronyd' }}"
  when: ansible_virtualization_type != "docker"
  ignore_errors: yes

- name: Enabling all services - Upstart/System V way
  service:
    name: "{{ 'ntp' if ansible_os_family == 'Debian' else 'chronyd' }}"
    state: started
    enabled: yes
  ignore_errors: yes

#
# Creating .hushlogin inside all user's home
################################################################################
- name: Check if .hushlogin exists in /etc/skel
  ansible.builtin.stat:
    path: /etc/skel/.hushlogin
  register: skel_hushlogin_stat
  when: enable_hushlogin is defined

- name: Create .hushlogin inside the /etc/skel
  ansible.builtin.file:
    path: /etc/skel/.hushlogin
    state: touch
    owner: root
    group: root
    mode: 0600
  when: enable_hushlogin is defined and not skel_hushlogin_stat.stat.exists

- name: Check if .hushlogin exists in users home
  ansible.builtin.stat:
    path: ~/.hushlogin
  register: user_hushlogin_stat
  when: enable_hushlogin is defined

- name: Create .hushlogin inside users home
  ansible.builtin.file:
    path: ~/.hushlogin
    state: touch
    owner: root
    group: root
    mode: 0600
  when: enable_hushlogin is defined and not user_hushlogin_stat.stat.exists

#
# Editing SSH for more security
################################################################################
- name: Modifing SSH's default port
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#Port 22'
    line: 'Port {{ ssh_port }}'
    state: present
  when: ssh_port is defined

- name: Disable SSH root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'PermitRootLogin yes'
    line: 'PermitRootLogin no'
    state: present
