version: 2.1
jobs:
  ansible-galaxy:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Ansible
          command: pip install ansible
      - run:
          name: Create ansible.cfg
          command: printf '[defaults]\nroles_path=../' >ansible.cfg
      - run:
          name: Run Ansible Playbook
          command: ansible-playbook -i tests/inventory tests/test.yml --syntax-check
      - run:
          name: Deploy to Ansible Galaxy
          command: ansible-galaxy role import lucascbeyeler baseline
workflows:
  version: 2
  build-and-test:
    jobs:
      - ansible-galaxy